### ISSUE TITLE
Forward to URL

### ISSUE THREAD

**Issue by george-i** [roxma/SMS-Forward#1]
Great idea.
Can you point out where in the code should I make a HTTP request, to forward the SMS?

To understand the context, I will receive messages with 4 digits numbers (1254, 4568, etc). Then I want to send this number to a server.

Found

**Comment by roxma** [comment]
https://github.com/roxma/SMS-Forward/blob/master/app/src/main/java/roxma/org/sms_forward/SmsListener.java
